### ISSUE TITLE
NullPointerException on runUiThread

### ISSUE THREAD

**Issue by koenhendriks** [cornedor/mayhem#14] opened 2015-01-19 09:05 UTC
>java.lang.NullPointerException: Attempt to invoke virtual method 'void >android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
>at nl.deltionmobiel.rooster.ScheduleFragment.noDataAvailable(ScheduleFragment.java:175)
>at nl.deltionmobiel.rooster.Data$1.run(Data.java:143)
>at java.lang.Thread.run(Thread.java:818)

**Comment by cornedor** [comment] 2015-01-19 11:21
Duplicate of #11

**Closed by cornedor** 2015-01-19 11:21 UTC
Labels: bug
